# Generated by Django 5.1.5 on 2025-03-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetail',
            name='assets',
            field=models.ImageField(blank=True, null=True, upload_to='task_asset'),
        ),
    ]
