# Generated by Django 5.1.5 on 2025-03-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_taskdetail_assets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetail',
            name='assets',
        ),
        migrations.AddField(
            model_name='taskdetail',
            name='asset',
            field=models.ImageField(blank=True, default='tasks_asset/default_img.jpg', null=True, upload_to='tasks_asset'),
        ),
    ]
