# Generated by Django 5.1.5 on 2025-03-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_taskdetail_assets_taskdetail_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='asset',
            field=models.ImageField(blank=True, default='static/images/no_image.png', null=True, upload_to='tasks_asset'),
        ),
    ]
