# Generated by Django 5.1.5 on 2025-05-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_taskdetail_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='asset',
            field=models.ImageField(blank=True, default='tasks_asset/default_img.jpg', null=True, upload_to='tasks_asset'),
        ),
    ]
